title: <p align="center"> Kiet Nguyen </p>

logo: "/images/profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="mailto:kietng.work@email.com">Email</a> |
  <a href="https://www.linkedin.com/in/kietn1/">LinkedIn</a> |
  <a href="https://github.com/kietngwork">GitHub</a>

  </p>
  
  <p align="justify">
  I completed MS degree in Business Analytics at California State Polytechnic University, Pomona.
  <br><br>
  I am seeking a full-time opportunity to leverage my technical expertise and background in data analysis, marketing, banking, and finance.
  <br><br>
  
  </p>

   <p align="justify">
    <strong>Certifications</strong><br>
    • Google Data Analytics Professional Certificate<br>
    • Microsoft Power BI Data Analyst (PL-300)<br>
    • AWS Cloud Practitioner<br>
    
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
