title: <p align="center"> Kiet Nguyen </p>

logo: "/images/profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf" target="_blank">Resume</a> |
  <a href="mailto:kietng.work@email.com">Email</a> |
  <a href="https://www.linkedin.com/in/kietn1/" target="_blank" rel="noopener noreferrer">LinkedIn</a> |
  <a href="https://github.com/kietngwork" target="_blank" rel="noopener noreferrer">GitHub</a>

  </p>
  
  <p align="left">
 Iâ€™m looking for a full-time role where I can use data to uncover insights, support smarter decisions, and drive meaningful results in marketing, banking, and finance.
  <br><br>
 Master of Science in Business Analytics - California State Polytechnic University, Pomona
  <br><br>
  
   </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
