title: <p align="center"> Kiet Nguyen </p>

logo: "/images/profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/KietNguyen_Resume.pdf" target="_blank">Resume</a> |
  <a href="mailto:kietng.work@email.com">Email</a> |
  <a href="https://www.linkedin.com/in/kietn1/" target="_blank" rel="noopener noreferrer">LinkedIn</a> |
  <a href="https://github.com/kietngwork" target="_blank" rel="noopener noreferrer">GitHub</a>

  </p>
  
  <p align="left">
 I realized the part of marketing I enjoyed most was analyzing performance, testing hypotheses, and using data to drive decisions. Over time, I took on more analytical workâ€”building reports, analyzing funnels, and evaluating experiments which naturally led me toward a Business & Data Analyst role.
  <br><br>
 MS in Business Analytics - California State Polytechnic University, Pomona
  <br><br>
  
   </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
