title: <p align="center"> Kiet Nguyen </p>

logo: "/images/profile.png?raw=true"

description:
  <p align="center">
    <a href="/about/" class="nav-btn">About</a>
    <a href="https://kietngwork.github.io/portfolio/" class="nav-btn" target="_blank">Portfolio</a>
    <a href="/pdf/resume.pdf" class="nav-btn" target="_blank">Resume</a>
    <a href="https://www.linkedin.com/in/kietn1/" class="nav-btn" target="_blank">LinkedIn</a>
    <a href="https://github.com/kietngwork" class="nav-btn" target="_blank">GitHub</a>
  </div>

  </p>
  
  <p align="justify">
  I completed MS degree in Business Analytics at California State Polytechnic University, Pomona.
  <br><br>
  I am seeking a full-time opportunity to leverage my technical expertise and background in data analysis, marketing, banking, and finance.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
